# basic information
title = "> laststation.net"
base_url = "https://laststation.net/"
description = "This is the last station on the (whole inter-) net. At least for me."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
generate_feed = true
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
theme = "zola-bearblog"

taxonomies = [
  {name = "categories", feed = true},
  {name = "tags", feed = true},
]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
date_format="%d %b, %Y"

[[extra.main_menu]]
name = "Blog"
url = "@/blog/_index.md"

